"""empty message

Revision ID: 17669076d533
Revises: 495933bd8817
Create Date: 2018-06-28 11:11:53.407176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17669076d533'
down_revision = '495933bd8817'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entidade', sa.Column('cnpj', sa.String(length=14), nullable=True))
    op.create_unique_constraint(None, 'entidade', ['cnpj'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entidade', type_='unique')
    op.drop_column('entidade', 'cnpj')
    # ### end Alembic commands ###
