"""empty message

Revision ID: 4f3286eab53d
Revises: c1b6dbac523a
Create Date: 2018-06-12 19:04:49.400288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f3286eab53d'
down_revision = 'c1b6dbac523a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(length=25), nullable=True),
    sa.Column('bairro', sa.String(length=25), nullable=True),
    sa.Column('cidade', sa.String(length=25), nullable=True),
    sa.Column('estado', sa.String(length=25), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('cep', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('telefone', sa.Integer(), nullable=True),
    sa.Column('tipo_entidade', sa.Integer(), nullable=True),
    sa.Column('id_endereco', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('rasao_social', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=25), nullable=True),
    sa.Column('password', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('motorista')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motorista',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('nomeMotorista', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('dtNascMotorista', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('cpfMotorista', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('modCarro', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('sexoMotorista', mysql.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('usuario')
    op.drop_table('entidade')
    op.drop_table('endereco')
    # ### end Alembic commands ###
