"""empty message

Revision ID: 555522f6227b
Revises: 17669076d533
Create Date: 2018-06-29 00:32:03.692423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '555522f6227b'
down_revision = '17669076d533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipamento_fiscalizacao', sa.Column('latitude', sa.Integer(), nullable=True))
    op.add_column('equipamento_fiscalizacao', sa.Column('longitude', sa.Integer(), nullable=True))
    op.add_column('equipamento_fiscalizacao', sa.Column('tipo', sa.String(length=100), nullable=True))
    op.add_column('equipamento_fiscalizacao', sa.Column('velocidade_regulamentada', sa.Integer(), nullable=True))
    op.drop_column('equipamento_fiscalizacao', 'velociade')
    op.drop_column('equipamento_fiscalizacao', 'id_endereco')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipamento_fiscalizacao', sa.Column('id_endereco', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('equipamento_fiscalizacao', sa.Column('velociade', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('equipamento_fiscalizacao', 'velocidade_regulamentada')
    op.drop_column('equipamento_fiscalizacao', 'tipo')
    op.drop_column('equipamento_fiscalizacao', 'longitude')
    op.drop_column('equipamento_fiscalizacao', 'latitude')
    # ### end Alembic commands ###
