"""empty message

Revision ID: 55dbcf92bf97
Revises: dd280c9c1593
Create Date: 2018-06-29 00:59:44.446925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55dbcf92bf97'
down_revision = 'dd280c9c1593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipamento_fiscalizacao', 'velocidade_regulamentada')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipamento_fiscalizacao', sa.Column('velocidade_regulamentada', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
