"""empty message

Revision ID: 673b8025c010
Revises: 55dbcf92bf97
Create Date: 2018-06-29 01:00:04.186465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673b8025c010'
down_revision = '55dbcf92bf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipamento_fiscalizacao', sa.Column('velocidade_regulamentada', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipamento_fiscalizacao', 'velocidade_regulamentada')
    # ### end Alembic commands ###
