"""empty message

Revision ID: 77257b746a95
Revises: ea763c298be5
Create Date: 2018-06-20 21:02:21.074917

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '77257b746a95'
down_revision = 'ea763c298be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acidente',
                    sa.Column('cod', sa.Integer(), nullable=False),
                    sa.Column('id_endereco', sa.Integer(), nullable=True),
                    sa.Column('cod_envolvido', sa.Integer(), nullable=True),
                    sa.Column('tipo', sa.String(length=50), nullable=True),
                    sa.Column('situacao', sa.String(length=50), nullable=True),
                    sa.Column('data', sa.String(length=10), nullable=True),
                    sa.Column('hora', sa.String(length=10), nullable=True),
                    sa.Column('natureza', sa.String(length=50), nullable=True),
                    sa.Column('descricao', sa.String(length=100), nullable=True),
                    sa.Column('qtd_vitmas', sa.Integer(), nullable=True),
                    sa.Column('qtd_vitmas_fatais', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('cod')
                    )
    op.create_table('assinatura',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_entidade', sa.Integer(), nullable=True),
                    sa.Column('id_pacote_informacao', sa.Integer(), nullable=True),
                    sa.Column('data_compra', sa.String(length=10), nullable=True),
                    sa.Column('validade', sa.String(length=10), nullable=True),
                    sa.Column('preco_compra', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('camera_transito',
                    sa.Column('cod', sa.Integer(), nullable=False),
                    sa.Column('id_endereco', sa.Integer(), nullable=True),
                    sa.Column('nome', sa.String(length=10), nullable=True),
                    sa.PrimaryKeyConstraint('cod')
                    )
    op.create_table('coordenadas',
                    sa.Column('cod', sa.Integer(), nullable=False),
                    sa.Column('latitude', sa.Integer(), nullable=True),
                    sa.Column('longitude', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('cod')
                    )
    op.create_table('envolvido',
                    sa.Column('cod', sa.Integer(), nullable=False),
                    sa.Column('qtd_auto', sa.Integer(), nullable=True),
                    sa.Column('qtd_moto', sa.Integer(), nullable=True),
                    sa.Column('qtd_ciclom', sa.Integer(), nullable=True),
                    sa.Column('qtd_ciclista', sa.Integer(), nullable=True),
                    sa.Column('qtd_pedestre', sa.Integer(), nullable=True),
                    sa.Column('qtd_onibus', sa.Integer(), nullable=True),
                    sa.Column('qtd_caminhao', sa.Integer(), nullable=True),
                    sa.Column('qtd_viatura', sa.Integer(), nullable=True),
                    sa.Column('qtd_outros', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('cod')
                    )
    op.create_table('equipamento_fiscalizacao',
                    sa.Column('cod_equipamento', sa.Integer(), nullable=False),
                    sa.Column('id_endereco', sa.Integer(), nullable=True),
                    sa.Column('velociade', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('cod_equipamento')
                    )
    op.create_table('infracao',
                    sa.Column('cod_infracao', sa.Integer(), nullable=False),
                    sa.Column('amaparo_legal', sa.String(length=50), nullable=True),
                    sa.Column('descricao_infracao', sa.String(length=300), nullable=True),
                    sa.PrimaryKeyConstraint('cod_infracao')
                    )
    op.create_table('pacote_informacao',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('nome_pacote', sa.String(length=30), nullable=True),
                    sa.Column('tipo_entidade', sa.Integer(), nullable=True),
                    sa.Column('ano_pacote', sa.String(length=10), nullable=True),
                    sa.Column('duracao', sa.String(length=10), nullable=True),
                    sa.Column('descricao', sa.String(length=50), nullable=True),
                    sa.Column('valor', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('registro_infracao',
                    sa.Column('cod', sa.Integer(), nullable=False),
                    sa.Column('id_endereco', sa.Integer(), nullable=True),
                    sa.Column('cod_infracao', sa.Integer(), nullable=True),
                    sa.Column('agente_equipamento', sa.String(length=50), nullable=True),
                    sa.Column('hora_infracao', sa.String(length=10), nullable=True),
                    sa.Column('data_infracao', sa.String(length=10), nullable=True),
                    sa.Column('data_implantacao', sa.String(length=10), nullable=True),
                    sa.PrimaryKeyConstraint('cod')
                    )
    op.create_table('semaforo',
                    sa.Column('cod_semaforo', sa.Integer(), nullable=False),
                    sa.Column('id_endereco', sa.Integer(), nullable=True),
                    sa.Column('funcionamento', sa.String(length=10), nullable=True),
                    sa.Column('utilizacao', sa.String(length=20), nullable=True),
                    sa.Column('sinalsonoro', sa.String(length=1), nullable=True),
                    sa.Column('sinalizadorciclista', sa.String(length=1), nullable=True),
                    sa.PrimaryKeyConstraint('cod_semaforo')
                    )
    op.create_table('sugestao',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_entidade', sa.Integer(), nullable=True),
                    sa.Column('mensagem', sa.String(length=150), nullable=True),
                    sa.Column('data', sa.String(length=10), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sugestao')
    op.drop_table('semaforo')
    op.drop_table('registro_infracao')
    op.drop_table('pacote_informacao')
    op.drop_table('infracao')
    op.drop_table('equipamento_fiscalizacao')
    op.drop_table('envolvido')
    op.drop_table('coordenadas')
    op.drop_table('camera_transito')
    op.drop_table('assinatura')
    op.drop_table('acidente')
    # ### end Alembic commands ###
