"""empty message

Revision ID: 8e2b2ac79fcc
Revises: e72ce72ae286
Create Date: 2018-07-08 23:37:58.329872

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8e2b2ac79fcc'
down_revision = 'e72ce72ae286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entidade', sa.Column('id_endereco', sa.Integer(), nullable=True))
    op.add_column('entidade', sa.Column('id_usuario', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entidade', 'enderecoEntidade', ['id_endereco'], ['id'])
    op.create_foreign_key(None, 'entidade', 'usuario', ['id_usuario'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entidade', type_='foreignkey')
    op.drop_constraint(None, 'entidade', type_='foreignkey')
    op.drop_column('entidade', 'id_usuario')
    op.drop_column('entidade', 'id_endereco')
    # ### end Alembic commands ###
