"""empty message

Revision ID: 8fdac7ad162a
Revises: 4a404b41b556
Create Date: 2018-06-29 00:57:05.269926

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fdac7ad162a'
down_revision = '4a404b41b556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipamento_fiscalizacao', 'longitude')
    op.drop_column('equipamento_fiscalizacao', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipamento_fiscalizacao', sa.Column('latitude', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('equipamento_fiscalizacao', sa.Column('longitude', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
