"""empty message

Revision ID: c1b6dbac523a
Revises: 
Create Date: 2018-06-12 17:20:07.213950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1b6dbac523a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motorista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nomeMotorista', sa.String(length=10), nullable=True),
    sa.Column('dtNascMotorista', sa.String(length=10), nullable=True),
    sa.Column('cpfMotorista', sa.Integer(), nullable=True),
    sa.Column('modCarro', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('sexoMotorista', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('motorista')
    # ### end Alembic commands ###
