"""empty message

Revision ID: c8e29da7b0d1
Revises: ef8a10023694
Create Date: 2018-06-28 10:52:08.190909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8e29da7b0d1'
down_revision = 'ef8a10023694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('entidade_ibfk_2', 'entidade', type_='foreignkey')
    op.drop_constraint('entidade_ibfk_1', 'entidade', type_='foreignkey')
    op.drop_column('entidade', 'id_endereco')
    op.drop_column('entidade', 'id_usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entidade', sa.Column('id_usuario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('entidade', sa.Column('id_endereco', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('entidade_ibfk_1', 'entidade', 'endereco', ['id_endereco'], ['id'])
    op.create_foreign_key('entidade_ibfk_2', 'entidade', 'usuario', ['id_usuario'], ['id'])
    # ### end Alembic commands ###
