"""empty message

Revision ID: dd280c9c1593
Revises: 8fdac7ad162a
Create Date: 2018-06-29 00:57:22.990556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd280c9c1593'
down_revision = '8fdac7ad162a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('equipamento_fiscalizacao', sa.Column('latitude', sa.String(length=12), nullable=True))
    op.add_column('equipamento_fiscalizacao', sa.Column('longitude', sa.String(length=12), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('equipamento_fiscalizacao', 'longitude')
    op.drop_column('equipamento_fiscalizacao', 'latitude')
    # ### end Alembic commands ###
