"""empty message

Revision ID: e72ce72ae286
Revises: d50115b09e65
Create Date: 2018-07-08 23:16:50.894219

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e72ce72ae286'
down_revision = 'd50115b09e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'acidente', 'endereco', ['endereco_codlocal'], ['codlocal'])
    op.create_foreign_key(None, 'equipamento_fiscalizacao', 'endereco', ['endereco_codlocal'], ['codlocal'])
    op.create_foreign_key(None, 'registro_infracao', 'endereco', ['endereco_codlocal'], ['codlocal'])
    op.create_foreign_key(None, 'semaforo', 'endereco', ['endereco_codlocal'], ['codlocal'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'semaforo', type_='foreignkey')
    op.drop_constraint(None, 'registro_infracao', type_='foreignkey')
    op.drop_constraint(None, 'equipamento_fiscalizacao', type_='foreignkey')
    op.drop_constraint(None, 'acidente', type_='foreignkey')
    # ### end Alembic commands ###
