"""empty message

Revision ID: ea763c298be5
Revises: 
Create Date: 2018-06-14 16:22:07.777554

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ea763c298be5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('endereco',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('rua', sa.String(length=35), nullable=True),
                    sa.Column('bairro', sa.String(length=30), nullable=True),
                    sa.Column('cidade', sa.String(length=30), nullable=True),
                    sa.Column('estado', sa.String(length=35), nullable=True),
                    sa.Column('numero', sa.Integer(), nullable=True),
                    sa.Column('cep', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('entidade',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('cnpj', sa.Integer(), nullable=True),
                    sa.Column('estado', sa.Boolean(), nullable=True),
                    sa.Column('telefone', sa.Integer(), nullable=True),
                    sa.Column('tipo_entidade', sa.Integer(), nullable=True),
                    sa.Column('id_endereco', sa.Integer(), nullable=True),
                    sa.Column('id_usuario', sa.Integer(), nullable=True),
                    sa.Column('razao_social', sa.String(length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('usuario',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=40), nullable=True),
                    sa.Column('password', sa.String(length=16), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('entidade')
    op.drop_table('endereco')
    # ### end Alembic commands ###
